# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .assumable_role import *
from .provider import *
from .user import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "awsIam",
  "mod": "index",
  "fqn": "jkisk_pulumi_aws_iam",
  "classes": {
   "awsIam:index:AssumableRole": "AssumableRole",
   "awsIam:index:User": "User"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "awsIam",
  "token": "pulumi:providers:awsIam",
  "fqn": "jkisk_pulumi_aws_iam",
  "class": "Provider"
 }
]
"""
)
