// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./assumableRole";
export * from "./iamRoleForServiceAccount";
export * from "./provider";
export * from "./user";

// Import resources to register:
import { AssumableRole } from "./assumableRole";
import { IamRoleForServiceAccount } from "./iamRoleForServiceAccount";
import { User } from "./user";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "awsIam:index:AssumableRole":
                return new AssumableRole(name, <any>undefined, { urn })
            case "awsIam:index:IamRoleForServiceAccount":
                return new IamRoleForServiceAccount(name, <any>undefined, { urn })
            case "awsIam:index:User":
                return new User(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("awsIam", "index", _module)

import { Provider } from "./provider";

pulumi.runtime.registerResourcePackage("awsIam", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:awsIam") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
