// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class User extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'awsIam:index:User';

    /**
     * Returns true if the given object is an instance of User.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is User {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === User.__pulumiType;
    }


    /**
     * Create a User resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.createIamAccessKey === undefined) && !opts.urn) {
                throw new Error("Missing required property 'createIamAccessKey'");
            }
            if ((!args || args.createUserLoginProfile === undefined) && !opts.urn) {
                throw new Error("Missing required property 'createUserLoginProfile'");
            }
            resourceInputs["createIamAccessKey"] = args ? args.createIamAccessKey : undefined;
            resourceInputs["createUserLoginProfile"] = args ? args.createUserLoginProfile : undefined;
            resourceInputs["forceDestroy"] = args ? args.forceDestroy : undefined;
            resourceInputs["passwordLength"] = args ? args.passwordLength : undefined;
            resourceInputs["passwordResetRequired"] = args ? args.passwordResetRequired : undefined;
            resourceInputs["path"] = args ? args.path : undefined;
            resourceInputs["permissionsBoundary"] = args ? args.permissionsBoundary : undefined;
            resourceInputs["pgpKey"] = args ? args.pgpKey : undefined;
            resourceInputs["sshKeyEncoding"] = args ? args.sshKeyEncoding : undefined;
            resourceInputs["sshPublicKey"] = args ? args.sshPublicKey : undefined;
            resourceInputs["uploadIamUserSshKey"] = args ? args.uploadIamUserSshKey : undefined;
        } else {
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(User.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a User resource.
 */
export interface UserArgs {
    /**
     * Boolean to determine whether to create an IAM access key
     */
    createIamAccessKey: pulumi.Input<boolean>;
    /**
     * Boolean to determine whether to create an IAM user login profile
     */
    createUserLoginProfile: pulumi.Input<boolean>;
    forceDestroy?: pulumi.Input<boolean>;
    passwordLength?: pulumi.Input<number>;
    passwordResetRequired?: pulumi.Input<boolean>;
    path?: pulumi.Input<string>;
    permissionsBoundary?: pulumi.Input<string>;
    pgpKey?: pulumi.Input<string>;
    sshKeyEncoding?: pulumi.Input<string>;
    sshPublicKey?: pulumi.Input<string>;
    uploadIamUserSshKey?: pulumi.Input<boolean>;
}
